# Generated by Django 4.2.11 on 2024-03-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmarks',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
