# Generated by Django 4.2.11 on 2024-03-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_reportcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_repor_card_generation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_repor_card_generation')},
        ),
    ]
